tp_botanico/carrito/urls.py
from . import views
from django.urls import path

app_name = "carrito"

urlpatterns = [
    path('agregar/<int:producto_id>/', views.agregar_producto, name='agregar'), 
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name='eliminar'),    
    path('restar/<int:producto_id>/', views.restar_producto, name='restar'),    
    path('limpiar/', views.limpiar_carrito, name='limpiar'),        
]

tp_botanico/publica/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.index, name='inicio'),
    path('nosotros', views.nosotros, name='nosotros'),
    path('contacto', views.contacto, name='contacto'),
    path('productos', views.productos, name='productos'),
    path('plantas', views.plantas, name='plantas'),
    path('club', views.club, name='club'),
    path('crearpost', views.post, name='crearpost'),
    path('perfil', views.perfil, name='perfil'),
    path('perfil/<str:username>', views.perfil, name='crearpost'),
    path('seguir/<str:username>', views.seguir, name='seguir'),
    path('noseguir/<str:username>', views.noSeguir, name='noseguir'),
    path('productocaro/', views.productocaro, name='productocaro'),
    path('productobarato', views.productobarato, name='productobarato'),
    path('Staff', views.staff, name='Staff'),
]

tp_botanico/tp_botanico/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("publica.urls")),
    path('', include("login_registro.urls")),
    path('carrito', include("carrito.urls"))
]

urlpatterns+=static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

tp_botanico/publica/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.

class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    precio = models.FloatField()
    imagen = models.ImageField(upload_to="producto", null=True)
    stock  = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.nombre}"

class Planta(Producto):
    SOL = 'Sol'
    SOMBRA = 'Sombra'
    INTERIOR = 'Interior'
    EXTERIOR = 'Exterior'
    
    AMBIENTE_CHOICES = (
        (SOL, 'Sol'),
        (SOMBRA, 'Sombra'),
        (INTERIOR, 'Interior'),
        (EXTERIOR, 'Exterior')
    )
    ambiente = models.CharField(
        max_length=10,
        choices=AMBIENTE_CHOICES,
        default=INTERIOR)
    


class GrupoPlanta(models.Model):
    codigo = models.CharField(max_length=128)
    descripcion = models.ManyToManyField(Planta, through="TipoPlanta")
   
    def __str__(self):
        return self.codigo

class TipoPlanta(models.Model):
    producto = models.ForeignKey(Planta, on_delete=models.CASCADE)
    grupos = models.ForeignKey(GrupoPlanta, on_delete=models.CASCADE)
    caracteristicas = models.CharField(max_length=164)

    def __str__(self):
        return self.caracteristicas


class Factura(models.Model):
    numero_factura = models.IntegerField(default=0)
    fecha = models.DateTimeField(default=timezone.now)
    cuit   = models.CharField(max_length=128)
    importe = models.FloatField()


    def __str__(self):
        return f"{self.numero_factura}"


class ProductoFactura(models.Model):
    factura = models.ForeignKey(Factura, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    linea = models.IntegerField(default=0)
    cantidad =  models.IntegerField(default=0)
    precio = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.factura,self.producto}"




class Perfil(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    imagen = models.ImageField(default="./perfil/plantita.png", upload_to="perfil", null=True)

    def __str__(self):
        return f"Perfil de {self.user}"
    
    def seguidores(self):
        user_ids = Relacion.objects.filter(desde_user=self.user)\
                            .values_list("a_user_id", flat=True)
        return User.objects.filter(id__in=user_ids)
    
    def seguidos(self):
        user_ids = Relacion.objects.filter(a_user=self.user)\
                            .values_list("desde_user_id", flat=True)
        return User.objects.filter(id__in=user_ids)
    
class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="post")
    fechaPost = models.DateTimeField(default=timezone.now)
    contenido = models.TextField()

    class Meta:
        ordering = ["-fechaPost"]
    
    def __str__(self):
        return f"{self.user.username}: {self.contenido}"

class Relacion(models.Model):
    desde_user = models.ForeignKey(User, related_name="relacion", on_delete=models.CASCADE)
    a_user = models.ForeignKey(User, related_name="a_relacion", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.desde_user} a {self.a_user}"

    

tp_botanico/publica/forms.py
from django import forms
from django.forms import ValidationError
from .models import Post

def nombre_valido(value):
    if not value:
        raise ValidationError("El campo 'Nombre' es obligatotio",code="Nombre incompleto")
    else:
        if len(value.split(" ")) > 1:
            list_nombres = value.split(" ")
            for nombre in list_nombres:
                if not nombre.isalpha():
                    raise ValidationError("No intriducir números ni caracteres especiales", code="Nombre no alfanumerico")                    
        else:
            raise ValidationError("Introducir nombre y apellido", code="Nombre incompleto")

def validarMensaje(value):
    if len(value.split(" ")) < 6:
        raise ValidationError("Por favor, brinda más detalles en tu mensaje", code="mensaje muy corto")                    


class contacto_form(forms.Form):
    nombre = forms.CharField(
        max_length=50, 
        label="", 
        validators=(nombre_valido,),
        widget=forms.TextInput(attrs={'class': 'contacto-campo', 'placeholder': 'Nombre y apellido'})        
        )
    mail = forms.EmailField(
        label="", 
        widget=forms.EmailInput(attrs={'class': 'contacto-campo','placeholder': 'E-mail'})
        )
    asunto = forms.CharField(
        max_length=40, label="", 
        widget=forms.TextInput(attrs={'class': 'contacto-campo', 'placeholder': 'Asunto'})
        )
    mensaje = forms.CharField(
        label="", 
        validators=(validarMensaje,),
        widget=forms.Textarea(attrs={'class': 'contacto-campo contacto-area', 'placeholder': 'Ingrese su mensaje', "rows": "5"})
        )


class Post_form(forms.ModelForm):
    contenido = forms.CharField(label="", widget=forms.Textarea(attrs={"rows": "2", 'placeholder': 'Escribe tu post...'}))

    class Meta:
        model= Post
        fields = ['contenido']

tp_botanico/publica/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from django.core.mail import send_mail
from django.conf import settings

from .models import Producto
from .models import Planta

from .forms import contacto_form, Post_form
from .models import *

# Create your views here.

def index(request):
    return render(request, 'publica/index.html')

def nosotros(request):
    return render(request, 'publica/nosotros.html')

def staff(request):
    return render(request, 'admin')

def productos(request):
    wambi = request.GET.get('Ambientes')
    #print(a) 
    if wambi=="Todos" or wambi==None:
       listado_productos = Producto.objects.all()
    else:
       listado_productos = Producto.objects.all().filter(ambiente=wambi)
    #listado_productos = Producto.objects.filter(precio__range=(1200, 9999))
    return render(request, 'publica/productos.html', {"productos":listado_productos})

def plantas(request):
    wambi = request.GET.get('Ambientes')
    #print(a) 
    if wambi=="Todos" or wambi==None:
       listado_productos = Planta.objects.all()
    else:
       listado_productos = Planta.objects.all().filter(ambiente=wambi)
    #listado_productos = Producto.objects.filter(precio__range=(1200, 9999))
    return render(request, 'publica/productos.html', {"productos":listado_productos})


def productocaro(request):
    listado_productos = Producto.objects.filter(precio__range=(5000, 9999999999))
    return render(request, 'publica/productos.html', {"productos":listado_productos})

def productobarato(request):
    listado_productos = Producto.objects.filter(precio__range=(1, 4999))
    #listado_productos = Producto.objects.all().filter(ambiente=loque)

    return render(request, 'publica/productos.html', {"productos":listado_productos})


def contacto(request):
    mensaje = None #Ver clase 17
    #Si recibe la URL por POST toma los datos del formulario
    if request.method == "POST":
        formContacto = contacto_form(request.POST)
        #Se valida los datos is_valid()
        if formContacto.is_valid():
            messages.info(request,"El formulario se ha enviado con exito!")
            mjs = f'De: {formContacto.cleaned_data["nombre"]}, mail: {formContacto.cleaned_data["mail"]}, asunto: {formContacto.cleaned_data["asunto"]}, mensaje: {formContacto.cleaned_data["mensaje"]}'
            mjs_html = f"""
                <p>De: {formContacto.cleaned_data["nombre"]} <a href="mailto:{formContacto.cleaned_data["mail"]}">
                {formContacto.cleaned_data["mail"]}</a></p>
                <p>Asunto: {formContacto.cleaned_data["asunto"]}</p>
                <p>mensaje: {formContacto.cleaned_data["mensaje"]}</p>
            """  
            asunto = f"CONSULTA DE LA PÁGINA: {formContacto.cleaned_data['asunto']}"
            send_mail(
                asunto,
                mjs,
                settings.EMAIL_HOST_USER,
                [settings.RECIPIENT_ADDRESS],
                fail_silently=False,
                html_message=mjs_html
            )
            formContacto = contacto_form()      
        else:
          messages.info(request,"Error: verificar los campos del formulario")           
    #Si la URL es recibida por el metodo GET crea un formulario en blanco (sin datos)
    else:
        formContacto = contacto_form()
    return render(request, "publica/contacto.html", {"formContacto": formContacto})
    
@login_required
def club(request):
    posts = Post.objects.all()    
    return render(request, 'publica/club.html', {"posts": posts})

def post(request):
    get_user = get_object_or_404(User, pk=request.user.pk)
    if request.method == "POST":
        form = Post_form(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = get_user
            post.save()
            messages.success(request, "Tu post ha sido creado!")
            return redirect("club")
    else:
        form = Post_form()
    return render(request, 'publica/crearPost.html', {"form": form})

def perfil(request,username=None):
    get_user = request.user
    if username and username != get_user.username:
        user = User.objects.get(username=username)
        posts = user.post.all()
    else:
        posts = get_user.post.all()
        user = get_user

    context = {
        'user':user,
        'posts':posts
    }
    return render(request, 'publica/perfil.html', context)

def seguir(request, username):
    get_user = request.user
    a_user = User.objects.get(username=username)
    a_user_id = a_user
    rel = Relacion(desde_user=get_user, a_user=a_user_id)
    rel.save()
    return redirect('club')

def noSeguir(request, username):
    get_user = request.user
    a_user = User.objects.get(username=username)
    a_user_id = a_user
    rel = Relacion.objects.filter(desde_user=get_user.id, a_user=a_user_id).get()
    rel.delete()
    return redirect('club')

tp_botanico/templates/publica/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static "./publica/css/estilos.css" %}?v=1.3" />
	  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    {% block estilo %}{% endblock estilo %}
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Red+Hat+Display&family=Roboto&display=swap"
      rel="stylesheet"
    />
    <script src="https://kit.fontawesome.com/562201e81a.js" crossorigin="anonymous"></script>    
    <title>{% block titulo %}{% endblock titulo %}</title>        
  </head>

  <body>
    <header>
      <div class="redes-header">
        <a
          href="https://www.facebook.com/"
          class="fa fa-facebook"
          target="_blank"
        ></a>
        <a
          href="https://www.instagram.com/puntohuertaok/"
          class="fa fa-instagram"
          target="_blank"
        ></a>
        <a
          href="https://twitter.com/?lang=es"
          class="fa fa-twitter"
          target="_blank"
        ></a>
        <a
          href="https://www.youtube.com/channel/UC0KEON-vDcBgbkjhIXh7hgQ"
          class="fa fa-youtube"
          target="_blank"
        ></a>
      </div>
    </header>

    <nav class="posicion-nav navbar navbar-expand-lg bg-light sticky-top">
      <div class="container-fluid">
        <a class="navbar-brand" href={% url 'inicio' %}>
          <img src={% static "./publica/img/logo.png"%} alt="logo marca" width="50" height="auto" />
          Botánica
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href={% url 'inicio' %}
                >Inicio</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href={% url 'productos' %}>Productos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href={% url 'nosotros' %}>Nosotros</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href={% url 'club' %}>Club</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href={% url 'contacto' %}>Contacto</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href={% url 'Staff' %}>Staff</a>
            </li>
          </ul>
          
          {%if user.is_authenticated %}
          <div class="buttons_loguer">
            <li style="list-style-type: none;" class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  ¡Bienvenid@ <b>{{user.username}}</b>!
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href={% url 'perfil' %}>Mi perfil</a></li> 
                <li><a class="dropdown-item" href={% url 'cerrar_sesion' %}>Cerrar sesión</a></li>                
              </ul>
            </li>
            
          </div>
          {% else %}
          <div class="buttons">
            <a href={% url 'login' %}><button class="login-button btn btn-outline-primary me-2">Iniciar sesión</button></a>
            <a href={% url 'registro' %}><button class="signup-button btn btn-primary" type="submit">Registrarse</button></a>
          </div>
          {% endif %} 
          
        </div>
      </div>
    </nav>

	<main>
		{% block main %}{% endblock main %}
	</main>
    
    <footer class="pie-pagina">
    	<div class="grupo-2">
			<small>&copy; 2022 <b>BOTANICA</b> - Todos los Derechos Reservados.</small>
      	</div>
    </footer>

    <!-- Scripts de JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    {% block jsScript %}{% endblock jsScript %}
  </body>
</html>

tp_botanico/templates/publica/bkproductos.html
{% extends './base.html' %} 

{%block estilo %} 
  {% load static %} 
  <link rel="stylesheet" href="{% static "./publica/css/productos.css" %}?v=1.2"> 
{% endblock estilo %} 

{% block titulo %}Tienda online{% endblock titulo %}

{%block main %}

	<section class="contenedor">
		<!-- Contenedor de los productos-->
		<div class="contenedor-items">
			{%for producto in productos%}
				<div class="item">
					<span class="titulo-item">{{producto.nombre}}</span>
					<img src= {{producto.imagen.url}} alt="imagen del producto {{producto.titulo}}" class="img-item">
					<span class="precio-item">$ {{producto.precio}}</span>
					<a href="{% url 'carrito:agregar' producto.id %}" class="boton-item">Agregar al carrito</a>
				</div>			
			{%endfor%}			
		</div>

		<!-- Carrito de compras -->
		<div class="carrito">
			<div class="header-carrito">
				<h2>Tu carrito</h2>
			</div>

			{%if request.session.carrito.items %}
						{%for key, value in request.session.carrito.items%}
						<tr>
							<div class="carrito-item">
								<img src= {{value.imagen}}  alt="" width="80px">
								<div class="carrito-item-detalle">
									<span class="carrito-item-titulo">{{value.nombre}}</span>
									<div class="selector-cantidad">
										<a href="{% url 'carrito:restar' value.producto_id %}"><i class="fa-solid fa-minus restar-cantidad"></i></a>
										<input type="text" value="{{value.cantidad}}" class="carrito-item-cantidad" disabled>
										<a href="{% url 'carrito:agregar' value.producto_id %}"><i class="fa-solid fa-plus"></i></a>
									</div>
									<span class="carrito-item-precio">{{value.precio}}</span>
								</div>
								<a href="{% url 'carrito:eliminar' value.producto_id %}"><span class="btn-eliminar"><i class="fa-solid fa-trash"></i></span></a>
							</div>
						</tr>
						{%endfor%}
				{% else %}
						<div class="alert alert-danger text-center m-1">
							Sin productos
						</div>
				{%endif%}
			<div class="carrito-items">				
			</div>

			<div class="carrito-total">
				<div class="fila">
					<strong>Tu total</strong>
					<span class="carrito-precio-total">$ {{total_carrito}}</span>
				</div>
				<button class="btn-pagar">Pagar<i class="fa-solid fa-bag-shopping"></i></button>
			</div>
		</div>
		
		<!-- Carrito de compras prueba
		<div class="carrito2">
			<table class="table table-bordered">
				<thead>
					<tr>
						<th colspan="3" class="text-center">
							Carrito de compras
						</th>
					</tr>
					<tr>
						<th>Producto</th>
						<th>Cantidad</th>
						<th>Precio</th>
					</tr>
				</thead>

				<tbody>
					{%if request.session.carrito.items %}
						{%for key, value in request.session.carrito.items%}
						<tr>
							<td>{{value.nombre}}</td>
							<td>{{value.precio}}</td>
						</tr>
						{%endfor%}
					{% else %}
					<tr>
						<td colspan=3>
							<div class="alert alert-danger text-center">
								Sin producto
							</div>
						</td>
					</tr>
					{% endif %}

				</tbody>
	
			</table>
		</div>
		-->

	</section>

{% endblock main %}

{% block jsScript %}
<script src="{% static './publica/js/producto.js' %}?v=1.1"></script>
{% endblock jsScript %}

tp_botanico/templates/publica/club.html
{% extends './base.html' %} 
{% load humanize %}
{%block estilo %} 
  {% load static %} 
  <link rel="stylesheet" href="{% static "./publica/css/club.css" %}?v=1.2">   
{% endblock estilo %} 
{% block titulo %}Club{% endblock titulo %}

{%block main %}

<div class="principal">
	<nav class="second-nav">
		<a class="new" href="{% url 'crearpost' %}">Crear nuevo post</a>
	</nav>
	
	{% for post in posts %}
		<article>
			<div class="container-article">
				<img src= "{{post.user.perfil.imagen.url}}" alt="imagen de perfil de {{post.user.username}}">
				<div>
					<h2 class="username"><a href="{% url 'perfil' %}/{{post.user.username}}">{{post.user.username}}</a></h2>
					<i class="clock"></i>
					<time data-time="#">{{post.fechaPost|naturaltime}}</time>
					<div class="post">{{post.contenido}}</div>
				</div>
			</div>
		</article>
	{% endfor %}

</div>




{% endblock main%}

tp_botanico/templates/publica/contacto.html
{% extends './base.html' %} 
{%block estilo %} 
  {% load static %} 
  <link rel="stylesheet" href="{% static "./publica/css/contacto.css" %}?v=1.2">   
{% endblock estilo %} 

{% block titulo %}Contacto{% endblock titulo %}

{%block main %}
	<div class="contenedor-contacto">
		<div class="contacto-caja">
			<div class="caja-izq"></div>
			<div class="caja-der">
				<h2>Contacto</h2>
				<form novalidate id="contacto-form" action="" method="post">
					{% csrf_token %}
   					{%for campo in formContacto%}
					   <div>
							<div>
								{{campo}}													
							</div>
							<div class="msj-error">{{campo.errors}}</div>
						</div>
					{%endfor%}
					<button class="contacto-enviar">Enviar</button>					
				</form>	
				<div>					
					{%for message in messages%}
						<div class="mt-2 alert alert-info" role="alert">
							{{message}}
						</div>
					{%endfor%}
				</div>			
			</div>
		</div>
	</div>	
{% endblock main %}

{% block jsScript %}
<script src="{% static './publica/js/contacto.js' %}?v=1.1"></script>
{% endblock jsScript %}

tp_botanico/templates/publica/crearPost.html
{% extends './base.html' %} 
{% load humanize %}
{%block estilo %} 
  {% load static %} 
  <link rel="stylesheet" href="{% static "./publica/css/club.css" %}?v=1.2">   
{% endblock estilo %} 
{% block titulo %}Crear nuevo post{% endblock titulo %}

{%block main %}
	<div class="principal">
		<form action="" method="POST">
			{% csrf_token %}
			{{form}}
			<button type="submit">Post</button>
		</form>
	</div>


{% endblock main%}

tp_botanico/templates/publica/productos.html
{% extends './base.html' %} 

{%block estilo %} 
  {% load static %} 
  <link rel="stylesheet" href="{% static "./publica/css/productos.css" %}?v=1.2"> 
{% endblock estilo %} 

{% block titulo %}Tienda online{% endblock titulo %}

{%block main %}
    <a href={% url 'productos' %}>
	    <button class="btn-lg ver_mas">Todos los Productos</button>
    </a>
	<a href={% url 'plantas' %}>
	    <button class="btn-lg ver_mas">Plantas</button>
    </a>
    <a href={% url 'productocaro' %}>
	    <button class="btn-lg ver_mas">Caras</button>
    </a>
	<a href={% url 'productobarato' %}>
	    <button class="btn-lg ver_mas">Baratas</button>
    </a>
 
	<form action="#">
		<label for="lang">Ambiente:</label>
		<select name="Ambientes" id="lang">
		  <option value="Todos">Todos</option>
		  <option value="Sol">Sol</option>
		  <option value="Sombra">Sombra</option>
		  <option value="Interior">Interior</option>
		  <option value="Exterior">Exterior</option>
		</select>
		<input type="submit" value="Buscar Planta" />
    </form>

	<section class="contenedor">
		<!-- Contenedor de los productos-->
		<div class="contenedor-items">
			{%for producto in productos%}
				<div class="item">
					<span class="titulo-item">{{producto.nombre}}</span>
					<img src= {{producto.imagen.url}} alt="imagen del producto {{producto.titulo}}" class="img-item">
					<span class="precio-item">$ {{producto.precio}}</span>
					<span class="Stocky"> Stock: {{producto.stock}}</span><br>
					<span class="Amb"> Ambiente: {{producto.ambiente}}</span>

					<a href="{% url 'carrito:agregar' producto.id %}" class="boton-item">Agregar al carrito</a>
				</div>			
			{%endfor%}			
		</div>

		<!-- Carrito de compras -->
		<div class="carrito">
			<div class="header-carrito">
				<h2>Tu carrito</h2>
			</div>

			{%if request.session.carrito.items %}
						{%for key, value in request.session.carrito.items%}
						<tr>
							<div class="carrito-item">
								<img src= {{value.imagen}}  alt="" width="80px">
								<div class="carrito-item-detalle">
									<span class="carrito-item-titulo">{{value.nombre}}</span>
									<div class="selector-cantidad">
										<a href="{% url 'carrito:restar' value.producto_id %}"><i class="fa-solid fa-minus restar-cantidad"></i></a>
										<input type="text" value="{{value.cantidad}}" class="carrito-item-cantidad" disabled>
										<a href="{% url 'carrito:agregar' value.producto_id %}"><i class="fa-solid fa-plus"></i></a>
									</div>
									<span class="carrito-item-precio">{{value.precio}}</span>
								</div>
								<a href="{% url 'carrito:eliminar' value.producto_id %}"><span class="btn-eliminar"><i class="fa-solid fa-trash"></i></span></a>
							</div>
						</tr>
						{%endfor%}
				{% else %}
						<div class="alert alert-danger text-center m-1">
							Sin productos
						</div>
				{%endif%}
			<div class="carrito-items">
				<!--
				<div class="carrito-item">
					<img src={% static './publica/img/planta8.avif' %}  alt="" width="80px">
					<div class="carrito-item-detalle">
						<span class="carrito-item-titulo">nombre de producto</span>
						<div class="selector-cantidad">
							<i class="fa-solid fa-minus restar-cantidad"></i>
							<input type="text" value="1" class="carrito-item-cantidad" disabled>
							<i class="fa-solid fa-plus sumar-cantidad"></i>
						</div>
						<span class="carrito-item-precio">$11.111</span>
					</div>
					<span class="btn-eliminar"><i class="fa-solid fa-trash"></i></span>
				</div>
				-->
			</div>

			<div class="carrito-total">
				<div class="fila">
					<!--<strong>Total</strong>
					 <span class="carrito-precio-total">$ {{producto.precio}}</span>  -->
					<span class="precio-item">Total $ </span>
				</div>
				<button class="btn-pagar">Pagar<i class="fa-solid fa-bag-shopping"></i></button>

			</div>
		</div>
		
		<!-- Carrito de compras prueba
		<div class="carrito2">
			<table class="table table-bordered">
				<thead>
					<tr>
						<th colspan="3" class="text-center">
							Carrito de compras
						</th>
					</tr>
					<tr>
						<th>Producto</th>
						<th>Cantidad</th>
						<th>Precio</th>
					</tr>
				</thead>

				<tbody>
					{%if request.session.carrito.items %}
						{%for key, value in request.session.carrito.items%}
						<tr>
							<td>{{value.nombre}}</td>
							<td>{{value.precio}}</td>
						</tr>
						{%endfor%}
					{% else %}
					<tr>
						<td colspan=3>
							<div class="alert alert-danger text-center">
								Sin producto
							</div>
						</td>
					</tr>
					{% endif %}

				</tbody>
	
			</table>
		</div>
		-->

	</section>

{% endblock main %}

{% block jsScript %}
<script src="{% static './publica/js/producto.js' %}?v=1.1"></script>
{% endblock jsScript %}